apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: slettix-analytics
  labels:
    app: minio
    app.kubernetes.io/part-of: slettix-analytics
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: minio.slettix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-console
                port:
                  number: 9001
