apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superset
  namespace: slettix-analytics
  labels:
    app: superset
    app.kubernetes.io/part-of: slettix-analytics
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: superset.slettix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superset
                port:
                  number: 8088
