apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: slettix-analytics
  labels:
    app: superset
    app.kubernetes.io/part-of: slettix-analytics
    app.kubernetes.io/component: superset
spec:
  type: LoadBalancer
  selector:
    app: superset
  ports:
    - name: http
      port: 8088
      targetPort: 8088
