apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataportal
  namespace: slettix-analytics
  labels:
    app: dataportal
    app.kubernetes.io/part-of: slettix-analytics
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: dataportal.slettix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dataportal
                port:
                  number: 8090
